tasks:
  - init: npm install && npm run build
    command: npm run start
ports: 
  - port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components@0.0.27:6f8dLBHJ6bHiAsfAwvXZNg==
    - paulmolluzzo.convert-css-in-js@1.1.3:YnjK47pXScU3DMFfQzkkOw==